name: CD

on:
  release:
    types:
      - published

jobs:
  cd:
    uses: halo-sigs/reusable-workflows/.github/workflows/theme-cd.yaml@v3
    permissions:
      contents: write
    with:
      app-id: app-squauk4h
      skip-appstore-release: false
      node-version: 22
      pnpm-version: 9
